kind: DataSetConfiguration
apiVersion: client.uor-framework.io/v1alpha1
collection:
  files:
    - file: /mnt/iso/arch/*
      attributes:
        boot: default
    - file: /mnt/iso/arch/boot/x86_64/initramfs-linux-hardened.img
      attributes:
        boot: default
    - file: /mnt/iso/EFI/*
      attributes:
        boot: default
    - file: /mnt/iso/syslinux/*
      attributes:
        boot: default
    - file: empourus/config/init.sh
      attributes:
        script: default
    - file: empourus/config/large-ram.sh
      attributes:
        script: large-ram
    - file: empourus/config/00-ipv6.sh
      attributes:
        script: ipv6
    - file: empourus/config/kubeadm/kubeadm-config-office.yaml
      attributes:
        cluster: office
    - file: empourus/config/kubeadm/kubeadm-config-datacenter.yaml
      attributes:
        cluster: datacenter
    - file: empourus/config/kubeadm/kubeadm-config-home.yaml
      attributes:
        cluster: home

#The attributes field in the YAML file allows for the specification of different attributes for each file in the data set. In this particular configuration, the attributes include boot, script, and cluster, but other attributes could be used instead or in addition to these. The use and possible values for each attribute would depend on the specific application or system that the data set is being used for.
#For example, if the data set is being used for a bootable system, the boot attribute could be used to specify different boot options, such as default, rescue, or recovery. The script attribute could be used to specify different types of scripts that are included in the data set, such as initialization, maintenance, or cleanup scripts. The cluster attribute could be used to specify different cluster configurations, such as for an office, datacenter, or home environment.
#In general, the possibilities for attribute configuration in this YAML file are limited only by the specific needs of the application or system that the data set is being used for, and the attributes and values used can be customized to suit those needs.



