kind: DataSetConfiguration
apiVersion: client.uor-framework.io/v1alpha1
collection:
  files:
    - file: arch/*
      attributes:
        system: default
    - file: arch/boot/x86_64/initramfs-linux-hardened.img
      attributes:
        system: default
    - file: EFI/*
      attributes:
        system: default
    - file: syslinux/*
      attributes:
        system: default
