apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: httpd:2.4
        ports:
        - containerPort: 80
        volumeMounts:
        - name: init-config    
          mountPath: /usr/local/apache2/htdocs/init.sh
          subPath: init.sh
          readOnly: true
        - name: kubeadm-config
          mountPath: /usr/local/apache2/htdocs/kubeadm-config.yaml
          subPath: kubeadm-config.yaml
          readOnly: true
        - name: iso-volume
          mountPath: /usr/local/apache2/htdocs/iso
      volumes:
      - name: init-config
        configMap:
          name: init-config
      - name: kubeadm-config
        secret:
          secretName: kubeadm-config
      - name: iso-volume
        persistentVolumeClaim:
          claimName: iso-claim
