apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: local
  name: apache-service
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.9.9
  selector:
    app: apache
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
