apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
nodeRegistration:
  name: ephemeral-$UUID
  taints: []
  kubeletExtraArgs:
    resolv-conf: /etc/resolv.conf
    cgroup-driver: systemd
    node-labels: "net.mcserverhosting.node/ephemeral=true,kubernetes.io/os=MCSH"
    cpu-manager-policy: static
    memory-manager-policy: Static
    reserved-cpus: "0"
    reserved-memory: "0:memory=1Gi"
    fail-swap-on: "false"
    max-pods: "220"
    seccomp-default: "true"
    feature-gates: "SeccompDefault=true,NodeSwap=true"
    root-dir: /mnt/kubelet
discovery:
  bootstrapToken:
    apiServerEndpoint: $ENDPOINT
    token: $TOKEN
    caCertHashes:
    - $CERTHASH
