apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
nodeRegistration:
  name: home-$UUID
  taints: []
  kubeletExtraArgs:
    resolv-conf: /etc/resolv.conf
    cgroup-driver: systemd
    node-labels: "net.sfxworks.workload/home=true"
    cpu-manager-policy: static
    reserved-cpus: "0"
    fail-swap-on: "false"
discovery:
  bootstrapToken:
    apiServerEndpoint: 192.168.5.1:6443
    token: u67ii0.wu3zzerkpaoo8zce
    caCertHashes:
    - sha256:37a0bbbb265ce1ba54c16d25ca268a253dbf07a604ffdcbb9d23b9147b4717e9
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: stable
controlPlaneEndpoint: 192.168.5.1:6443

#Even in changing these definitions and the kubeadm-config file there still lies something that is telling iboutu 192.168.8.1...i remember it was uhhhh...potential y cluster api endpoint settings. but thats here. but that isnt read in join config. 
# So is it perm in cluster config? controlPlaneEndpoint