name: Build ISO

on:
  push:
#    paths:
#    - 'baseline/*'
#    - '!baseline/README.md'
    branches:
      - main



jobs:
  build:
    name: Build ISO
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run iso make script
        run: docker run --privileged -v $PWD/baseline:/profile -v $PWD/customrepo:/customrepo ghcr.io/mcserverhosting-net/os/archiso:latest mkarchiso -v -w /tmp -o /profile/out /profile
      - name: Archive ISO artifact
        uses: actions/upload-artifact@v3
        with:
          name: archiso
          path: baseline/out/
          if-no-files-found: error
      - name: Copy ISO to remote server
        env:
          REMOTE_HOST: 208.73.137.196
          REMOTE_USER: root
          REMOTE_PATH: /srv/nfs/iso
          SSH_KEY: ${{ secrets.REMOTE_SSH_KEY }}
        run: |
          echo "$SSH_KEY" > private_key
          chmod 600 private_key
          scp -i private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r baseline/out/*.iso $REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH
          rm -f private_key
