name: Build ISO

on: [push]

jobs:
  build:
    name: Build ISO
    runs-on: ubuntu-latest
    steps:
      - name: Login to Harbor Registry
        uses: docker/login-action@v2
        with:
          registry: registry.service.mcserverhosting.net
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install empourus
        run: wget https://github.com/uor-framework/uor-client-go/releases/download/v0.3.0/uor-client-go-linux-amd64 && chmod +x uor-client-go-linux-amd64
      - name: Run iso make script
        run: docker run --privileged -v $PWD/baseline:/profile registry.service.mcserverhosting.net/library/archiso:latest mkarchiso -v -w /tmp -o /profile/out /profile -quiet=y
      - name: Mount ISO
        run: mkdir $PWD/empourus/boot && mount -o loop $PWD/baseline/out/* $PWD/empourus/boot
      - name: Build collection
        run: ./uor-client-go-linux-amd64 --loglevel=debug build collection empourus registry.service.mcserverhosting.net/dev/os:latest --dsconfig $PWD/empourus/dataset.yaml
      - name: Push collection
        run: ./uor-client-go-linux-amd64 --loglevel=debug push registry.service.mcserverhosting.net/dev/os:latest

