name: Build ISO

on: [push]

jobs:
  build:
    name: Build ISO
    runs-on: ubuntu-latest
    steps:
#      - name: Login to Harbor Registry
#        uses: docker/login-action@v2
#        with:
#          registry: registry.service.mcserverhosting.net
#          username: ${{ secrets.USERNAME }}
#          password: ${{ secrets.PASSWORD }}
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run iso make script
        run: docker run --privileged -v $PWD/baseline:/profile -v $PWD/customrepo:/customrepo registry.service.mcserverhosting.net/library/archiso:latest mkarchiso -v -w /tmp -o /profile/out /profile
      - name: Archive ISO artifact
        uses: actions/upload-artifact@v3
        with:
          name: archiso
          path: $PWD/baseline/out/
